server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://18.220.161.171:3306/quiz_app_db
    username: quiz_user
    password: Simo_5603
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
  logging:
    level:
      org.springframework.web: DEBUG
      org.hibernate.SQL: DEBUG

cors:
  allowed-origins: "http://18.220.161.171:3000,http://192.168.56.1:3000"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  allow-credentials: true
